version: "3.7"

networks:
  net:
    name: fabric_network

services:
  keycloak:
#     image: jboss/keycloak:11.0.2
    image: isharefoundation/ishare-satellite-keycloak:v11.0.2
    container_name: keycloak
    ports:
      - 8443:8443
    environment:
      - KEYCLOAK_USER=admin
      - KEYCLOAK_PASSWORD=admin
      - DB_VENDOR=postgres
      - DB_ADDR=keycloakpostgres
      - DB_DATABASE=keycloak
      - DB_USER=keycloak
      - DB_PASSWORD=keycloak
      - KEYCLOAK_IMPORT=/tmp/realm-test.json
    #   - PROXY_ADDRESS_FORWARDING=true
    #   - KEYCLOAK_FRONTEND_URL=https://isharefoundation-demo.krypc.com:6001/auth
    volumes:
      - ./realm-test.json:/tmp/realm-test.json
      - ../ssl/tls.crt:/etc/x509/https/tls.crt
      - ../ssl/tls.key:/etc/x509/https/tls.key
#      - ./myTheme:/opt/jboss/keycloak/themes/myTheme
#      - ./scripts/disable-theme-cache.cli:/opt/jboss/startup-scripts/disable-theme-cache.cli
    command: ["-Dkeycloak.profile.feature.upload_scripts=enabled"]
    restart: always
    depends_on:
      - keycloakpostgres
    networks:
    - net       

  keycloakpostgres:
    image: postgres:13.0-alpine
    container_name: keycloakpostgres
    ports:
      - 1432:5432
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    restart: always      
    volumes:
      - ./keycloakpostgres:/var/lib/postgresql/data
      - ./postgres:/docker-entrypoint-initdb.d
    networks:
    - net 


