version: 1.0.0
ishareConfig:
  middlewareConfig:
    type: satellite
    mode: "<ENVIRONMENT>"
    blockchain_middleware_url: "http://ishare_hlf:21001/api"
    explorerDb: postgresql://hppoc:password@explorerdb:5432/fabricexplorer?sslmode=disable
    offchainDb: postgresql://postgres:postgres@offchain_sat:5432/offchaindata?sslmode=disable 
#STARTS Scheduler Configuration to send Email Notifications for Network status and push the updates to the keycloak  
    emailID: "<SMTP_USER>"
    emailSecret: "<SMTP_PASSWORD>"
    emailPort: "<SMTP_PORT>"
    emailHost: "<SMTP_HOST>"
    displayName: "<DISPALY_NAME>"
    emailForceUpdate: false
    # If the emailForceUpdate values are true, then the middleware application will update the above email setup in the keycloak. (restart the ishare middleware service once the changes are incorporated)
#Sceduler Configuration to send Email Notifications for Network status ENDS    
    blockchain_details:
      admin: Admin
      channel_id: <CHANNEL_NAME>
      chaincode_id: <CHAINCODE_NAME>
      msp_id: <orgName>
      orgName: <orgName>
    forgotPasswordLink: "https://<UIHostName>/account/reset-password"
    partyId: <PartyId>
    partyName: <PartyName>
  platformURL: ""
  keyCloakConfig:
    domain: https://<KeycloakHostName>:8443
    clientId: frontend
    clientSecret: ""
    adminId: admin
    adminSecret: "admin"
    adminRealmName: master
    realmName: <UIHostName>
  versionConfig:
    currentVersion: 1.0
  cookieInfo:
    secrets:
      - super-secret-key-explorer-<orgName>
    cookieName: cookie-name-explorer-<orgName>
  listenAddr: ":21001"
  sslConfig:
    enable: false
    sslCertPath: ""
    sslKeyPath: ""

