version: "3.7"

networks:
  net:
    name: fabric_network

services:
 ishare_ui:
    image: isharefoundation/ishare-satellite-ui:v3.0

    container_name: ishare_ui
    ports:
    - 4200:80
    environment:
      - API_URL=https://<MiddlewareHostName>
      - AUTH_REDIRECT_URI=https://<UIHostName>
      - PROXY_ADDRESS_FORWARDING=true
      - KEYCLOAK_FRONTEND_URL=https://<KeycloakHostName>:8443/
      - REALM_NAME=<ORG_NAME>
    restart: always      
    networks:
    - net       
 nginx-proxy:
   image: nginx:1.25.1-alpine
   ports:
     - "443:443"
   volumes:
     - /var/run/docker.sock:/tmp/docker.sock:ro
     - ../ssl:/etc/ssl
     - ./nginx.conf:/etc/nginx/nginx.conf       
   restart: always
   network_mode: host     
  
