version: "2.1"

networks:
  net:
    name: fabric_network

services:

  explorerdb:
    # image: hyperledger/explorer-db:latest
    image: ghcr.io/hyperledger-labs/explorer-db:2.0.0
    container_name: explorerdb
    hostname: explorerdb
    environment:
      - DATABASE_DATABASE=fabricexplorer
      - DATABASE_USERNAME=hppoc
      - DATABASE_PASSWORD=password
    healthcheck:
      test: "pg_isready -h localhost -p 5432 -q -U postgres"
      interval: 30s
      timeout: 10s
      retries: 5
    ports:
      - 4432:5432
    restart: always      
    volumes:
      - ./docker_data/explorer_ishare:/var/lib/postgresql/data
    networks:
      - net

  explorer:
    # image: hyperledger/explorer:latest
    image: ghcr.io/hyperledger-labs/explorer:2.0.0
    container_name: explorer
    hostname: explorer
    environment:
      - DATABASE_HOST=explorerdb
      - DATABASE_DATABASE=fabricexplorer
      - DATABASE_USERNAME=hppoc
      - DATABASE_PASSWD=password
      - LOG_LEVEL_APP=debug
      - LOG_LEVEL_DB=debug
      - LOG_LEVEL_CONSOLE=info
      - LOG_CONSOLE_STDOUT=true
      - DISCOVERY_AS_LOCALHOST=false
    volumes:
      - ./explorer-config.json:/opt/explorer/app/platform/fabric/config.json
      - ./:/opt/explorer/app/platform/fabric/connection-profile
#      - /fabric-path/fabric-samples/test-network/organizations:/tmp/crypto
      - <cryptoPath>:/tmp/crypto
      - ./docker_data/walletstore_ishare:/opt/explorer/wallet
    restart: always      
    ports:
      - 8081:8080
    depends_on:
      explorerdb:
        condition: service_healthy
    networks:
      - net    
