version: "3.7"

networks:
  net:
    name: fabric_network

services:
  keycloak:
    image: isharefoundation/ishare-satellite-keycloak:v22.0.1
    container_name: keycloak
    ports:
      - 8443:8443
    environment:
      - KEYCLOAK_ADMIN=admin
      - KEYCLOAK_ADMIN_PASSWORD=admin
      - KC_HTTPS_PORT=8443
#      - KC_FILE=/tmp/realm-test.json
      - KC_HTTPS_CERTIFICATE_FILE=etc/x509/https/tls.crt
      - KC_HTTPS_CERTIFICATE_KEY_FILE=/etc/x509/https/tls.key
      - KC_DB=postgres
      - KC_DB_USERNAME=keycloak
      - KC_DB_PASSWORD=keycloak
      - KC_DB_URL_HOST=keycloakpostgres
      - KC_DB_URL=jdbc:postgresql://keycloakpostgres/keycloak
      - KC_HOSTNAME=<KEY_CLOAK_HOST_NAME>
      - KC_HOSTNAME_ADMIN_URL=https://<KEY_CLOAK_HOST_NAME>:8443/
      - KC_SPI_LOGIN_PROTOCOL_OPENID_CONNECT_LEGACY_LOGOUT_REDIRECT_URI=true
    volumes:
#      - ./realm-test.json:/tmp/realm-test.json
      - ./realm-test.json:/opt/keycloak/data/import/realm-test.json 
      - ../ssl/:/etc/x509/https/    
#      - ../ssl/tls.crt:/etc/x509/https/tls.crt
#      - ../ssl/tls.key:/etc/x509/https/tls.key
    command:
      - start --import-realm   
    restart: always
    depends_on:
      - keycloakpostgres
    networks:
    - net       

  keycloakpostgres:
    image: isharefoundation/postgressql:v14-alpine
    container_name: keycloakpostgres
    ports:
      - 1432:5432
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    restart: always      
    volumes:
      - ./keycloakpostgres:/var/lib/postgresql/data
      - ./postgres:/docker-entrypoint-initdb.d
    networks:
    - net 
